### PR TITLE
bug with ctrl+a

### PR DESCRIPTION
**Pull request by AvatarBlueray**
step to reproduce

open text editor, as example kate
write two lines, select one with mouse than ctrl+c,  than ctrl+a, ctrl+c, than run script. You will see one line selected by mouse.

this commit fix this problem/

### CODE REVIEW

**Comment by orithena** [comment]
This is working as designed: The mouse selection clipboard has precedence over the keyboard clipboard. Since I don't know whether I can retrieve the timestamps on the last clipboard entry in both clipboards, I chose this way. I'd accept a pull request that makes this configurable via command line switch.

**Comment by AvatarBlueray** [comment]
when i have mouse clipboard and ctrl+a i want to have last, my fix have last clippboard.

>I'd accept a pull request that makes this configurable via command line switch.
i understand you, but i don't want to do this way at this time, i will fork your(my) project

**Comment by AvatarBlueray** [comment]
i understand problem, revret case have same problem, i will think about it

**Comment by orithena** [comment]
Wait, you said your code always takes the last entry, no matter in which clipboard it ended up? This would be the behaviour I'd actually prefer, but I did not see it in the diff...

**Comment by AvatarBlueray** [comment]
xclip -o -selection clipboard   take all selection by mouse or keyboard
xclip -o take only mouse selection

i place xclip -o -selection clipboard  first

**Comment by orithena** [comment]
Okay, my trials from back when I wrote it seem to disagree with yours. I need to test the whole thing again (in a few days when I'm home again _and_ find the time, sorry).

**Comment by AvatarBlueray** [comment]
i am sory second commit is not for your master

**Comment by AvatarBlueray** [comment]
you doesn't have to merge my commit, i maintain my own brunch

**Pull request closed without merging**
